import datetime
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def generate_report(target_essid, target_bssid, channel, attacks_run):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report_dir = os.path.join(BASE_DIR, "report")
    os.makedirs(report_dir, exist_ok=True)
    fname = os.path.join(
        report_dir,
        f"pentest_{target_essid}_{datetime.datetime.now().strftime('%Y%m%d_%H%M')}.md"
    )

    loot_dir = os.path.join(BASE_DIR, "loot")

    def read_loot(path):
        full = os.path.join(loot_dir, path)
        if os.path.exists(full):
            with open(full) as f:
                return f.readlines()
        return []

    identities = read_loot("identities.txt")
    hashes     = read_loot("hashes.txt")
    passwords  = read_loot("cracked_passwords.txt")
    ad_creds   = read_loot("ad_creds.txt")

    if passwords or ad_creds:
        risk = "🔴 CRITICAL — Plaintext credentials obtained"
    elif hashes:
        risk = "🟠 HIGH — Credential hashes captured for offline cracking"
    elif identities:
        risk = "🟡 MEDIUM — User identities exposed"
    else:
        risk = "🟢 LOW — No credentials obtained"

    report = f"""# WPA2-Enterprise Penetration Test Report

**Date:** {timestamp}
**Tool:** EAPx Framework — github.com/babySAMRAT/eapx

---

## Target
| Field | Value |
|---|---|
| SSID | {target_essid} |
| BSSID | {target_bssid} |
| Channel | {channel} |
| Auth | WPA2-Enterprise (802.1X/EAP) |

## Attacks Run
{chr(10).join(f'- {a}' for a in attacks_run)}

## Risk Rating
{risk}

## EAP Identities Harvested ({len(identities)})
```
{''.join(identities) if identities else 'None captured'}
```

## Credential Hashes ({len(hashes)})
```
{''.join(hashes) if hashes else 'None captured'}
```

## Cracked Passwords ({len(passwords)})
```
{''.join(passwords) if passwords else 'None cracked'}
```

## Portal Credentials ({len(ad_creds)})
```
{''.join(ad_creds) if ad_creds else 'None captured'}
```

## Recommendations
- Enforce server certificate validation on all EAP supplicants
- Use EAP-TLS with client certificates instead of password-based EAP methods
- Implement 802.11w (Management Frame Protection) to prevent deauthentication attacks
- Deploy WIDS/WIPS to detect rogue access points
- Train users to verify certificate prompts before connecting

---
*Generated by EAPx Framework*
"""

    with open(fname, "w") as f:
        f.write(report)

    print(f"\n[+] Report saved → {fname}")
    return fname
